version: '3'
services:
    hackwpi:
        build: .
        command: bundle exec rails s --full-index -p 3000 -b '0.0.0.0'
        volumes:
            - .:/HackWPI
        ports:
            - "3000:3000"
